#ifndef MD_OUTPUT
#define MD_OUTPUT
#include <string.h>
#include <stdio.h>
#include <sys/stat.h>
#include "md_math.h"

void write_file(char* file_name, struct Particle* particles, int num_particles){
    mkdir("output/", 0777);
    char output_path[64] = "output/";
    strcat(output_path, file_name);
    strcat(output_path, ".xyz");

    printf("Writing to file: %s\n", output_path);

    FILE* file = fopen(output_path, "w+");
    
    fprintf(file, "%i\n", num_particles);
    fprintf(file, "Generated by c code.\n");

    for (int i=0; i<num_particles; i++){
        fprintf(file, "Ar %.6f %.6f %.6f\n", particles[i].x, particles[i].y, particles[i].z);
        fflush(file);
    }

    fclose(file);
}

#endif